//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharpNL.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SharpNL.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a
        ///a&apos;s
        ///able
        ///about
        ///above
        ///according
        ///accordingly
        ///across
        ///actually
        ///after
        ///afterwards
        ///again
        ///against
        ///ain&apos;t
        ///all
        ///allow
        ///allows
        ///almost
        ///alone
        ///along
        ///already
        ///also
        ///although
        ///always
        ///am
        ///among
        ///amongst
        ///an
        ///and
        ///another
        ///any
        ///anybody
        ///anyhow
        ///anyone
        ///anything
        ///anyway
        ///anyways
        ///anywhere
        ///apart
        ///appear
        ///appreciate
        ///appropriate
        ///are
        ///aren&apos;t
        ///around
        ///as
        ///aside
        ///ask
        ///asking
        ///associated
        ///at
        ///available
        ///away
        ///awfully
        ///b
        ///be
        ///became
        ///because
        ///become
        ///becomes
        ///becoming
        ///been
        ///before
        ///beforehand
        ///behind
        ///being
        ///believe
        ///below
        ///beside
        ///besides
        ///best
        ///better
        ///between
        ///beyond
        ///both
        ///brief
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string en_stopwords {
            get {
                return ResourceManager.GetString("en_stopwords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!--
        ///	Licensed to the Apache Software Foundation (ASF) under one
        ///	or more contributor license agreements.  See the NOTICE file
        ///	distributed with this work for additional information
        ///	regarding copyright ownership.  The ASF licenses this file
        ///	to you under the Apache License, Version 2.0 (the
        ///	&quot;License&quot;); you may not use this file except in compliance
        ///	with the License.  You may obtain a copy of the License at
        ///	
        ///	http://www.apache.org/licenses/LICENSE-2.0
        ///	
        ///	Unless required by applicable law or agreed to in  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ner_default_features {
            get {
                return ResourceManager.GetString("ner_default_features", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e 
        ///a 
        ///o 
        ///que 
        ///e 
        ///do 
        ///da 
        ///em 
        ///um 
        ///para 
        ///é 
        ///com 
        ///não 
        ///uma 
        ///os 
        ///no 
        ///se 
        ///na 
        ///por 
        ///mais 
        ///as 
        ///dos 
        ///como 
        ///mas 
        ///foi 
        ///ao 
        ///ele 
        ///das 
        ///tem 
        ///à 
        ///seu 
        ///sua 
        ///ou 
        ///ser 
        ///quando 
        ///muito 
        ///há 
        ///nos 
        ///já 
        ///está 
        ///eu 
        ///também 
        ///só 
        ///pelo 
        ///pela 
        ///até 
        ///isso 
        ///ela 
        ///entre 
        ///era 
        ///depois 
        ///sem 
        ///mesmo 
        ///aos 
        ///ter 
        ///seus 
        ///quem 
        ///nas 
        ///me 
        ///esse 
        ///eles 
        ///estão 
        ///você 
        ///tinha 
        ///foram 
        ///essa 
        ///num 
        ///nem 
        ///suas 
        ///meu 
        ///às 
        ///minha 
        ///têm 
        ///numa 
        ///pelos 
        ///elas 
        ///havia 
        ///seja 
        ///qual 
        ///será 
        ///nós 
        ///tenho 
        ///lhe 
        ///deles 
        ///essas 
        ///esses 
        ///pelas 
        ///este 
        ///fosse 
        ///dele 
        ///tu 
        ///te 
        ///vocês 
        ///vos 
        ///lhes 
        ///meus  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string pt_stopwords {
            get {
                return ResourceManager.GetString("pt_stopwords", resourceCulture);
            }
        }
    }
}
